server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_order?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: Zhou@1010
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: orderservice
  cloud:
    nacos:
      server-addr: localhost:8848 #nacos服务地址
      discovery:
        cluster-name: HZ # 集群名称
#        namespace: 58104e51-b50c-4d8a-83ef-99159718f506 # 命名空间，填ID  不在同一命名空间的微服务无法互相调用
#        ephemeral: false # 设置为非临时实例
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
ribbon:
  eager-load:
    clients:
      - userservice
    enabled: true

userservice:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule # 负载均衡规则
feign:
  client:
    config:
      serservice: # 针对某个微服务的配置
        loggerLevel: BASIC #  日志级别
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50